### ISSUE TITLE
random access bookmarks

### ISSUE THREAD

**Issue by KevinSeghetti** [atom/bookmarks#107]
## Summary

A feature I use in visual slickedit all the time is random access bookmarks.
I have the key bindings set up so that ctrl-1 through ctrl-9 set them, and alt-1 through alt-9 jump to them.

**Comment by rsese** [comment]
Thanks for the suggestion! Though this sounds like a useful idea for some people's workflows, we're not prioritizing new feature requests right now as mentioned in the issue template.

And for future issues, please completely fill out the issue template - also mentioned in the template is that we especially prefer if folks can consider if Atom's customizability can get provide the functionality you want.  Though I didn't find an existing community package that implements random access bookmarks, this functionality seems like a neat idea for a community package.

Thanks again for the idea but since this isn't something the team will work on, I'm going to close this issue.
