### ISSUE TITLE
cycle through bookmarks across files

### ISSUE THREAD

**Issue by KevinSeghetti** [atom/bookmarks#108]
## Summary

The way I am used to using bookmarks is across files. I would find the bookmarking system to be more useful if there were a next bookmark across files command, that went to the next file with a bookmark in it when activated on the last bookmark in the current file.

**Comment by rsese** [comment]
Thanks again for the suggestion - we noticed that this looks very close to https://github.com/atom/bookmarks/issues/19 so we'll close in favor of that issue.  You can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
