### ISSUE TITLE
Permanent bookmarks

### ISSUE THREAD

**Issue by Trudko** [atom/bookmarks#22]
Hi, is there plan to have permanent bookmarks, so they will be saved after I close the window or even Atom?  IMHO It would be nice if bookmarks would be permanent and there would be some list of existing bookmarks with description(similar like it is in Eclipse).

**Comment by Trudko** [comment]
@benogle bookmars doesn't work if I open folder using file --> open folder... I have tried this with atom --safe. I have to cd to folder and run atom from command line.

**Comment by benogle** [comment]
@Trudko I use them when I am working on more than one part of a largish file. Usually, I leave the file open for the entire duration of my work.

> bookmars doesn't work if I open folder using file --> open folder...

This definitely works for me. You are on the latest version (165), and you totally quit atom then started from the command line via `atom --safe`? Is there anything in the dev tools console?

**Comment by raphinesse** [comment]
@benogle I still see benefits from having persistent bookmarks. I wanted to use them while exploring a project for the first time, bookmarking interesting places that I might come back to later. Since I might need them *some other time* I don't want to keep the tabs open all the time.

I was thinking that an option like "Clear bookmarks on file close" could cater to both needs. What do you think about that?

**Comment by nietaki** [comment]
Even with the workflow described by @benogle my bookmarks don't persist (OSX):

1. open atom via command line in my project directory via `atom .`
1. create a bookmark using `cmd + f2`
1. close atom 
1. open atom again via command line in my the same directory via `atom .`

#### Expected result
bookmark persists

#### Actual result
no bookmarks there anymore

**Comment by viddo** [comment]
> … They are destroyed when you close the file, though.

I'm curious to _why_ it was done like this? Very much like @raphinesse mentioned above, I have similar use-cases where I'd like to be able to save bookmarks to revisit later. 

@benogle , Would you be open for a PR that enables this? E.g. adding persistent opt-in config option (off by default) so bookmarks works like it is now?

**Comment by Pendemonium** [comment]
I would like to save them, and I'll tell you why:

I'm setting up templates that designers (not programmers/coders) will be using with variables that need to be replaced by image links and file names. eg:

`<p><span class="keyInfo3">Main Landing Page Banner</span> : replace_with_file_name<br />`
`  <img src="replace_with_image_link" />`
`</p>`

I was excited to see that I could set up bookmarks to remember an entire section of a line, and not just the line itself.

So the plan was, they would open the file and just hit `F2` to step through all of the sections I've marked off and paste in the info, without having to worry about the rest of the code.

But, since the bookmarks are gone the moment I close the file, this isn't possible. At least I haven't found a way to do it yet.
