### ISSUE TITLE
Bookmark shortcut not working on mac

### ISSUE THREAD

**Issue by ahmadferdous** [atom/bookmarks#73]
Hi,

I could not get this bookmarks package working on mac. The shortcut to add/remove (cmd-F2) does not work.

Atom version: 1.11.2
Tried with both default bookmarks version (comes with Atom installation) 0.42 and the latest version 0.43.2.
OS X El Capitan (version 10.11.6)

Please help me. Thanks in advance!

**Comment by 50Wliu** [comment]
Have you tried safe mode (`atom --safe`)?  If it still doesn't work, can you open the keybinding resolver (<kbd>Cmd+.</kbd>) and see what it logs when you try the bookmarks keybinding?

**Comment by ahmadferdous** [comment]
@50Wliu : Thanks for your quick reply. I tried with safe mode and then I could bookmark.

Is bookmarks package supposed to work only in safe mode?

**Comment by Ben3eeE** [comment]
@ahmadferdous If you can't reproduce it in safe mode that means one of your installed community packages is causing this issue. I would recommend you check in the keybinding resolver <kbd>Cmd+.</kbd> to see if there is a conflicting keybinding.

Once you identify which package is causing the problem open an issue on that packages repository, or if it is a keybinding conflict you can simply set the conflicting keybind to another combination.

**Comment by mhussa** [comment]
I had a similar problem on el-capitan and when I used the keybinding resolver nothing would appear if I pressed F2.  Turns out there's a setting in System Preferences > Keyboard which needs to be set if you want to use the function keys as standard function keys.  I set it and it worked fine thereafter.

Thanks for creating such a useful package.

FYI: The other "challenge" with F2 was a binding conflict with tree-view:move but that's another story.  I disabled the tree view bindings because I hardly ever used them.

**Comment by gisellecc** [comment]
I had the same issue and I fixed it by enabling F keys as standard keys, like @mhussa suggested. This can be enabled by going to System Preferences > Keyboard.
![screen shot 2017-11-22 at 12 36 00 pm](https://user-images.githubusercontent.com/28316888/33146597-107b5d5e-cf82-11e7-9fac-dd60f6f93d24.png)
