### ISSUE TITLE
How can I change bookmark color?

### ISSUE THREAD

**Issue by getufkka** [atom/bookmarks#98]
I want to change bookmarks color. But I can't find the location where the bookmarks color setting is written. It probably is due to the bookmarks plugin is assembled to atom base package. Any help will be appreciated.

**Comment by pdonias** [comment]
Would something like this help?
```sh
$ find ~/.atom/compile-cache/less -name bookmarks.json -exec sed -i 's/#09C/#F00/g' {} \;
```
`F00` is red, change it to whatever you want. And don't forget to change the path to whatever folder you installed Atom in.

Probably not the best way to do it but I have no idea how to edit core packages.

**Comment by Ben3eeE** [comment]
You can edit your personal stylesheet to change the style that is defined here:

https://github.com/atom/bookmarks/blob/6f882e916684605e9727b4eb5e3af65a2a6740de/styles/bookmarks.less#L4-L12

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
